spring.application.name=chat-app
spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=continentalresources
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
jwt.secret=*********************
#goodluck finding the secret lad 4jdu5uriopehngmynriyhrjuyiokhly74jdu5uriopehngmynriyhrjuyiokhly74jdu5uriopehngmynriyhrjuyiokhly74jdu5uriopehngmynriyhrjuyiokhly74jdu5uriopehngmynriyhrjuyiokhly7
