spring.application.name=chat-app
spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=continentalresources
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
jwt.secret=4jdu5uriopehngmynriyhrjuyiokhly7